from typing import Protocol

from app.domain.entity.ai_analysis import AIAnalysis


class AIAnalysisRepository(Protocol):
    async def create(self, analysis: AIAnalysis) -> AIAnalysis: ...
    async def list_by_symbol(
        self, symbol: str, limit: int = 20
    ) -> list[AIAnalysis]: ...
    async def get(self, analysis_id: str) -> AIAnalysis | None: ...
    async def delete(self, analysis_id: str) -> bool: ...
