from datetime import datetime
from typing import Protocol

from app.domain.entity.stock import Candle, Fundamental, Stock, StockPrice


class StockRepository(Protocol):
    async def list_all(self) -> list[Stock]: ...
    async def search(self, query: str, limit: int = 20) -> list[Stock]: ...
    async def get_price(self, symbol: str) -> StockPrice | None: ...
    async def get_candles(
        self,
        symbol: str,
        period: str = "day",
        count: int = 120,
        before: datetime | None = None,
    ) -> list[Candle]: ...
    async def get_market_indices(self) -> list[StockPrice]: ...
    async def get_market_tickers(self, symbols: list[str]) -> list[StockPrice]: ...
    async def get_fundamental(self, symbol: str) -> Fundamental | None: ...
