from typing import Protocol

from app.domain.entity.trade import TradeEntry


class TradeRepository(Protocol):
    async def list(self) -> list[TradeEntry]: ...
    async def get(self, trade_id: str) -> TradeEntry | None: ...
    async def create(self, trade: TradeEntry) -> TradeEntry: ...
    async def update(self, trade_id: str, trade: TradeEntry) -> TradeEntry | None: ...
    async def delete(self, trade_id: str) -> bool: ...
